// ==========================================
// IMPORTS
// ==========================================

import { StatusCodes } from 'http-status-codes';
import Blog, { BLOG_STATUS, publishedFilter } from '../models/Blog.js';
import { NotFoundError, BadRequestError } from '../errors/customErrors.js';
import { ensureUniqueSlug, slugifyTitle } from '../utils/slugUtils.js';
import { sanitizeBlogContent } from '../utils/sanitizeUtils.js';
import { destroyBlogImage, isCloudinaryConfigured, uploadBlogImage } from '../config/cloudinary.js';

// ==========================================
// FIELDS THE CMS ACTUALLY SUPPORTS
// ==========================================
// Every write goes through this list. Nothing from req.body is ever spread onto
// a document, so a crafted payload cannot set _id, createdAt, __v, or anything
// else the CMS does not expose. `slug` is deliberately absent: slugs are
// generated by the server, never taken from a request.
const EDITABLE_FIELDS = ['title', 'description', 'content', 'author', 'image', 'status'];

const pickEditableFields = (body = {}) => {
  const picked = {};
  EDITABLE_FIELDS.forEach((field) => {
    if (body[field] !== undefined) {
      picked[field] = body[field];
    }
  });
  return picked;
};

const slugExists = async (candidate, excludeId) => {
  const query = { slug: candidate };
  if (excludeId) query._id = { $ne: excludeId };
  const existing = await Blog.findOne(query).select('_id').lean();
  return Boolean(existing);
};

const uploadImageIfPresent = async (file) => {
  if (!file) return null;
  if (!isCloudinaryConfigured()) {
    throw new BadRequestError('Image uploads are not available right now');
  }
  const result = await uploadBlogImage(file.buffer);
  return result.secure_url;
};

const normaliseStatus = (value) => (value === BLOG_STATUS.DRAFT ? BLOG_STATUS.DRAFT : BLOG_STATUS.PUBLISHED);

// ==========================================
// GET ALL BLOGS — PUBLIC
// GET /api/v1/blogs
// ==========================================
// Public reading never requires authentication. Drafts are filtered out here, and
// posts written before the `status` field existed still match (see
// publishedFilter) so nothing that is live today disappears.
export const getAllBlogs = async (req, res) => {
  const blogs = await Blog.find(publishedFilter()).sort({ createdAt: -1 });

  res.status(StatusCodes.OK).json({
    success: true,
    count: blogs.length,
    blogs,
  });
};

// ==========================================
// GET SINGLE BLOG BY SLUG — PUBLIC
// GET /api/v1/blogs/:slug
// ==========================================
export const getBlog = async (req, res) => {
  const { slug } = req.params;

  const blog = await Blog.findOne({ ...publishedFilter(), slug });

  // A draft is reported as "not found" rather than "forbidden", so the public
  // endpoint cannot be used to discover unpublished posts.
  if (!blog) {
    throw new NotFoundError('No blog found with that address');
  }

  res.status(StatusCodes.OK).json({ success: true, blog });
};

// ==========================================
// GET ALL BLOGS INCLUDING DRAFTS — ADMIN
// GET /api/v1/blogs/admin/all
// ==========================================
// Two path segments, so it can never be shadowed by the public /:slug route.
export const getAdminBlogs = async (req, res) => {
  const blogs = await Blog.find({}).sort({ createdAt: -1 });

  const publishedCount = blogs.filter((blog) => blog.status !== BLOG_STATUS.DRAFT).length;

  res.status(StatusCodes.OK).json({
    success: true,
    count: blogs.length,
    publishedCount,
    draftCount: blogs.length - publishedCount,
    blogs,
  });
};

// ==========================================
// GET SINGLE BLOG BY SLUG (ANY STATUS) — ADMIN
// GET /api/v1/blogs/admin/slug/:slug
// ==========================================
export const getAdminBlogBySlug = async (req, res) => {
  const { slug } = req.params;

  const blog = await Blog.findOne({ slug });
  if (!blog) {
    throw new NotFoundError('No blog found with that address');
  }

  res.status(StatusCodes.OK).json({ success: true, blog });
};

// ==========================================
// CREATE BLOG — ADMIN
// POST /api/v1/blogs
// ==========================================
export const createBlog = async (req, res) => {
  const fields = pickEditableFields(req.body);

  const status = normaliseStatus(fields.status);

  // The slug is derived from the title, then made unique. Two posts with the same
  // title get "the-title" and "the-title-2" instead of a database error.
  const slug = await ensureUniqueSlug(slugifyTitle(fields.title), slugExists);

  const image = (await uploadImageIfPresent(req.file)) ?? fields.image ?? null;

  const blog = await Blog.create({
    title: fields.title,
    description: fields.description,
    // Sanitized on the way in, before it is ever stored.
    content: sanitizeBlogContent(fields.content),
    author: fields.author,
    slug,
    image,
    status,
    // Drafts have no publish date. Published posts get the moment they went live.
    publishedAt: status === BLOG_STATUS.PUBLISHED ? new Date() : null,
  });

  res.status(StatusCodes.CREATED).json({
    success: true,
    msg: 'Blog created successfully',
    message: 'Blog created successfully',
    blog,
  });
};

// ==========================================
// UPDATE BLOG — ADMIN
// PATCH /api/v1/blogs/:id
// ==========================================
// Only the fields present in the request are touched.
//
// The slug is deliberately NOT regenerated. A published post's URL is a promise
// to anyone who linked to it, search engines included; changing the title must
// not move the page. If a slug ever has to change, that is a redirect decision,
// not a side effect of an edit.
export const updateBlog = async (req, res) => {
  const { id } = req.params;
  const fields = pickEditableFields(req.body);

  const blog = await Blog.findById(id);
  if (!blog) {
    throw new NotFoundError('No blog found with that id');
  }

  if (fields.title !== undefined) blog.title = fields.title;
  if (fields.description !== undefined) blog.description = fields.description;
  if (fields.content !== undefined) blog.content = sanitizeBlogContent(fields.content);
  if (fields.author !== undefined) blog.author = fields.author;
  if (fields.image !== undefined) blog.image = fields.image;

  if (fields.status !== undefined) {
    const nextStatus = normaliseStatus(fields.status);
    blog.status = nextStatus;

    // First publication stamps the date. Re-publishing later keeps the original
    // date so the post's history stays honest.
    if (nextStatus === BLOG_STATUS.PUBLISHED && !blog.publishedAt) {
      blog.publishedAt = new Date();
    }
  }

  const uploadedImageUrl = await uploadImageIfPresent(req.file);
  if (uploadedImageUrl) {
    // A replaced image is not deleted from Cloudinary. Links to the old asset
    // may already exist in social previews, cached pages and old posts, and a
    // broken image is a worse outcome than an unused file. The asset is only
    // removed when the post that owns it is deleted.
    blog.image = uploadedImageUrl;
  }

  await blog.save(); // timestamps keep updatedAt current

  res.status(StatusCodes.OK).json({
    success: true,
    msg: 'Blog updated successfully',
    message: 'Blog updated successfully',
    blog,
  });
};

// ==========================================
// DELETE BLOG — ADMIN
// DELETE /api/v1/blogs/:id
// ==========================================
export const deleteBlog = async (req, res) => {
  const { id } = req.params;

  const blog = await Blog.findByIdAndDelete(id);
  if (!blog) {
    throw new NotFoundError('No blog found with that id');
  }

  // The post is gone, so nothing references its image any more. Cleanup is
  // best-effort: a Cloudinary failure is logged and never fails the deletion.
  if (blog.image) {
    await destroyBlogImage(blog.image);
  }

  res.status(StatusCodes.OK).json({
    success: true,
    msg: 'Blog deleted successfully',
    message: 'Blog deleted successfully',
  });
};
